title: Soumita Das
logo: /assets/img/passport pic.jpg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/soumitadas/">LinkedIn</a> |
  <a href="https://github.com/soumitadas9">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  I have worked on many data modelling projects, reporting projects.
 
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
